---
- name: Install Macroscop in RedOS 7.3
  hosts: all
  become: yes

  tasks:
  - name: Add Macroscop repository
    ansible.builtin.shell: wget -O - http://packages.macroscop.com/rpm/install/macroscop-deps-centos.sh | bash
    register: showcentos

   - debug:
       var: showcentos

  - name: Install Macroscop
    ansible.builtin.yum:
     name:
     - macroscop
     state: latest
    environment:
     ACCEPT_EULA: 'y'