---
- name: Install Macroscop in RedHat (CentOS 7) and Debian 10
  hosts: all
  become: yes

  tasks:
  - name: Print OS Family
    debug: var=ansible_os_family

  - block:    # ===CentOS===

      - name: Install soft in RedHat (CentOS 7)
        ansible.builtin.yum:
          name:
          - wget
          state: latest

      - name: Add Macroscop repository
        ansible.builtin.shell: wget -O - http://packages.macroscop.com/rpm/install/macroscop-deps-centos.sh | bash
        register: showcentos

      - debug:
          var: showcentos

      - name: Install Macroscop in RedHat (CentOS 7)
        ansible.builtin.yum:
          name:
          - macroscop
          state: latest
        environment:
          ACCEPT_EULA: 'y'

    when: ansible_os_family == "RedHat"

  - block:    # ===Debian===

      - name: Add Macroscop repository
        ansible.builtin.shell: wget -O - http://packages.macroscop.com/deb/install/macroscop-deps-debian.sh | bash
        register: showubuntu

      - debug:
          var: showubuntu

      - name: Install soft in Debian 10
        ansible.builtin.apt:
          name: macroscop
          state: latest

    when: ansible_os_family == "Debian"